[package]
name = "rs-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
chrono = { version = "0.4.19", default-features = false, features = [ "clock", "std" ] }
jsonwebtoken = {version = "8", default-features = false }
serde = {version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
